import Head from "next/head";
import Header from "../components/header";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Builtree</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="relative">
                <div className="flex h-screen w-full justify-center items-center">
                    <h1 className="text-2xl text-gray-500">Coming soon...</h1>
                </div>
            </main>
        </div>
    );
}
