import Head from "next/head";
import Header from "../components/header";
import Maintained from "../components/projects/maintained";
import Affiliated from "../components/projects/affiliated";
import SideNav from "../components/side_nav";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Builtree</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="h-20" />
            <main className="relative">
                <Maintained />
                <Affiliated />
            </main>
        </div>
    );
}
